import numpy as np
import torch
import layers
from pre_processing import Task
from hypernetwork_arc import HyperNetworkARC
from primary_net_arc import PuzzleEmbedding

torch.set_default_dtype(torch.float32)


class ARCCompressorHyper:
    """
    VAE Decoder model for ARC-AGI that uses hypernetwork-generated weights.

    This is a modified version of ARCCompressor that replaces the Initializer
    with a HyperNetworkARC + PuzzleEmbedding, which generates all weights dynamically.

    Interface now matches primary_net.py pattern:
        - PuzzleEmbedding owns the embedding parameter
        - PuzzleEmbedding.forward(hypernetwork, task) generates weights
        - ARCCompressor uses these weights for forward pass

    Key differences from ARCCompressor:
        - Weights are generated by hypernetwork instead of randomly initialized
        - Puzzle embedding is optimized alongside hypernetwork weights
        - Enables weight sharing across multiple tasks via shared hypernetwork

    Architecture (same as ARCCompressor):
        - Decoding layer: Sample z ~ posterior, apply linear transform
        - 4 transformer-like blocks, each with:
            * share_up: Communication across multitensors (bottom-up)
            * softmax: Attention-like operations
            * cummax + shift: Directional operations
            * direction_share: Directional communication
            * nonlinear: SiLU activation
            * share_down: Communication across multitensors (top-down)
            * normalize: Layer normalization
        - Linear heads: Produce pixel logits and grid masks
    """

    # Define channel dimensions (same as ARCCompressor)
    n_layers = 4
    share_up_dim = 16
    share_down_dim = 8
    decoding_dim = 4
    softmax_dim = 2
    cummax_dim = 4
    shift_dim = 4
    nonlinear_dim = 16

    def channel_dim_fn(self, dims):
        """Return channel dimension based on presence of direction dimension."""
        return 16 if dims[2] == 0 else 8

    def __init__(self, task: Task, puzzle_embedding: PuzzleEmbedding, hypernetwork: HyperNetworkARC):
        """
        Create model using hypernetwork-generated weights.

        Interface mimics primary_net.py pattern:
            CIFAR-10: embedding.forward(hypernetwork) generates conv weights
            CompressARC: puzzle_embedding.forward(hypernetwork, task) generates all weights

        Args:
            task: The ARC-AGI task to solve
            puzzle_embedding: PuzzleEmbedding module (owns the embedding parameter)
            hypernetwork: Pre-initialized hypernetwork that generates weights
        """
        self.task = task
        self.multitensor_system = task.multitensor_system
        self.puzzle_embedding = puzzle_embedding
        self.hypernetwork = hypernetwork

        # Generate all weights using puzzle_embedding interface (matches primary_net.py)
        self.weights_list = puzzle_embedding(hypernetwork, task)

        # Unpack weights into named components
        self._unpack_weights()

    def _unpack_weights(self):
        """
        Unpack flat weights_list into named component structures.

        This is a simplified version - in practice, you'd need to carefully
        track indices to match the hypernetwork's generation order.
        For now, we'll regenerate the structured weights directly.
        """
        # Regenerate structured weights (simpler than index tracking)
        # In production, you'd want to optimize this to avoid redundant computation
        task = self.task
        hypernetwork = self.hypernetwork
        puzzle_embedding = self.puzzle_embedding
        multitensor_system = self.multitensor_system
        channel_dim_fn = self.channel_dim_fn

        device = puzzle_embedding.z.device
        metadata = torch.tensor([
            task.n_examples / 12.0,
            task.n_colors / 9.0,
            task.n_x / 30.0,
            task.n_y / 30.0
        ], dtype=torch.float32, device=device)

        h = torch.cat([puzzle_embedding.z, metadata])
        h = hypernetwork.body(h)

        # Regenerate components (matching hypernetwork order)
        self.multiposteriors = hypernetwork.generate_multiposterior(
            h, multitensor_system, 4
        )

        self.decode_weights = hypernetwork.generate_multilinear(
            h, multitensor_system, [4, channel_dim_fn]
        )

        self.target_capacities = hypernetwork.generate_multizeros(
            h, multitensor_system, [4]
        )

        # Layer weights
        self.share_up_weights = []
        self.share_down_weights = []
        self.softmax_weights = []
        self.cummax_weights = []
        self.shift_weights = []
        self.direction_share_weights = []
        self.nonlinear_weights = []

        for layer_idx in range(self.n_layers):
            layer_emb = torch.cat([h, torch.tensor([layer_idx / self.n_layers], device=device)])

            self.share_up_weights.append(
                hypernetwork.generate_multiresidual(layer_emb, multitensor_system, 16, 16, channel_dim_fn)
            )
            self.share_down_weights.append(
                hypernetwork.generate_multiresidual(layer_emb, multitensor_system, 8, 8, channel_dim_fn)
            )

            def softmax_output_fn(dims):
                return 2 * (2 ** (sum(dims[1:])) - 1)

            self.softmax_weights.append(
                hypernetwork.generate_multiresidual(layer_emb, multitensor_system, 2, softmax_output_fn, channel_dim_fn)
            )
            self.cummax_weights.append(
                hypernetwork.generate_multiresidual(layer_emb, multitensor_system, 4, 4, channel_dim_fn)
            )
            self.shift_weights.append(
                hypernetwork.generate_multiresidual(layer_emb, multitensor_system, 4, 4, channel_dim_fn)
            )
            self.direction_share_weights.append(
                hypernetwork.generate_multidirection_share(layer_emb, multitensor_system, channel_dim_fn)
            )
            self.nonlinear_weights.append(
                hypernetwork.generate_multiresidual(layer_emb, multitensor_system, 16, 16, channel_dim_fn)
            )

        self.head_weights = hypernetwork.generate_head(h, multitensor_system, channel_dim_fn)

        self.mask_weights = hypernetwork.generate_multilinear(
            h, multitensor_system,
            [channel_dim_fn([1, 0, 0, 1, 0]), 2],
            specific_dims=[1, 0, 0, 1, 0]
        )

        # Apply symmetrization
        for weight_list in [
            self.share_up_weights,
            self.share_down_weights,
            self.softmax_weights,
            self.cummax_weights,
            self.shift_weights,
            self.nonlinear_weights,
        ]:
            for weights in weight_list:
                hypernetwork.symmetrize_xy(weights, multitensor_system)

        for weights in self.direction_share_weights:
            hypernetwork.symmetrize_direction_sharing(weights, multitensor_system)

    def forward(self):
        """
        Forward pass (identical to ARCCompressor).

        Returns:
            output: [example, color, x, y, channel] tensor of pixel logits
            x_mask: [example, x, channel] mask scores
            y_mask: [example, y, channel] mask scores
            KL_amounts: List of KL divergence contributions
            KL_names: List of names for KL components
        """
        # Decoding layer
        x, KL_amounts, KL_names = layers.decode_latents(
            self.target_capacities, self.decode_weights, self.multiposteriors
        )

        # Transformer-like blocks
        for layer_num in range(self.n_layers):
            # Multitensor communication (bottom-up)
            x = layers.share_up(x, self.share_up_weights[layer_num])

            # Softmax layer
            x = layers.softmax(
                x, self.softmax_weights[layer_num],
                pre_norm=True, post_norm=False, use_bias=False
            )

            # Directional layers
            x = layers.cummax(
                x, self.cummax_weights[layer_num], self.multitensor_system.task.masks,
                pre_norm=False, post_norm=True, use_bias=False
            )
            x = layers.shift(
                x, self.shift_weights[layer_num], self.multitensor_system.task.masks,
                pre_norm=False, post_norm=True, use_bias=False
            )

            # Directional communication
            x = layers.direction_share(
                x, self.direction_share_weights[layer_num],
                pre_norm=True, use_bias=False
            )

            # Nonlinear layer
            x = layers.nonlinear(
                x, self.nonlinear_weights[layer_num],
                pre_norm=True, post_norm=False, use_bias=False
            )

            # Multitensor communication (top-down)
            x = layers.share_down(x, self.share_down_weights[layer_num])

            # Normalization
            x = layers.normalize(x)

        # Linear heads
        output = (
            layers.affine(x[[1, 1, 0, 1, 1]], self.head_weights, use_bias=False)
            + 100 * self.head_weights[[1, 1, 0, 1, 1]][1]
        )
        x_mask = layers.affine(x[[1, 0, 0, 1, 0]], self.mask_weights, use_bias=True)
        y_mask = layers.affine(x[[1, 0, 0, 0, 1]], self.mask_weights, use_bias=True)

        # Postprocessing
        x_mask, y_mask = layers.postprocess_mask(self.multitensor_system.task, x_mask, y_mask)

        return output, x_mask, y_mask, KL_amounts, KL_names
